# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: handleEnv
        run: if [ -z ${{secrets.TEST}} ];then echo hello;export TEST=${{secrets.TEST}};fi
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python -c "import os;print(os.environ)"

